version: '3.1'

services:
  db:
    build:
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: Oleksii
      POSTGRES_DB: bookmarks_db
    ports:
      - '5402:5432'
    env_file:
      - db_env.env
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
